spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:restful_demo;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS restful_demo # h2 database 連接位址
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: khc.yao.restfuldemo.controller
